name: Maven CI/CD

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Cache packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  

    - name: Build project
      run: mvn -B package --file pom.xml

  coverage:
    runs-on: ubuntu-latest
    name: Generate test coverage badge
    steps:

      - name: Generate a coverage value
        id: coverage
        run: |
          COVERAGE="$( parse-coverage-report )"
          echo "##[set-output name=lines;]${COVERAGE}%"

      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v1
        with:
          label: 'Test coverage'
          status: ${{ steps.coverage.outputs.lines }}
          color: 'blue,555,daf'
          path: badge.svg

  publish:
      runs-on: ubuntu-latest
      needs: [build]
      
      steps:
        - uses: actions/checkout@v4
        
        - uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 17
        
        - run: mvn -B package --file pom.xml -DskipTests
        
        - run: mkdir staging && cp target/*.jar staging
        
        - uses: actions/upload-artifact@v1
          with:
            name: Package
            path: staging
