name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Cache packages
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2  

    - name: Build project
      run: mvn -B package --file pom.xml

  publish:
      runs-on: ubuntu-latest
      needs: [build]
      
      steps:
        - uses: actions/checkout@v2
        
        - uses: actions/setup-java@v1
          with:
            java-version: 17
        
        - run: mvn -B package --file pom.xml -DskipTests
        
        - run: mkdir staging && cp target/*.jar staging
        
        - uses: actions/upload-artifact@v1
          with:
            name: Package
            path: staging
